services:
  - type: web
    name: citizen-voice
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false